- README.md
> Use 'experimental' stability badge

- .travis.yml
- .travis/settings.xml
> Automatic publishing of snapshots to Sonatype

- src/main/java/com/google/cloud/tools/maven/StageMojo.java
Fixes #22.
@loosebazooka @patflynn
> Primary and secondary Dockerfile location defaults

- README.md
- pom.xml
> Rename artifactId from gcp-app-maven-plugin to app-maven-plugin

- .travis.yml
- src/main/java/com/google/cloud/tools/maven/AppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/DeployMojo.java
- src/main/java/com/google/cloud/tools/maven/RunMojo.java
- src/main/java/com/google/cloud/tools/maven/StageMojo.java
- src/main/java/com/google/cloud/tools/maven/StopMojo.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java
- src/test/java/com/google/cloud/tools/maven/RunAsyncMojoTest.java
- src/test/java/com/google/cloud/tools/maven/RunMojoTest.java
- src/test/java/com/google/cloud/tools/maven/StageMojoTest.java
- src/test/java/com/google/cloud/tools/maven/StopMojoTest.java
> sync with common library package reorg

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
> Fail on non-zero process exit code

- src/main/java/com/google/cloud/tools/maven/StageMojo.java
Syncs up with the common library changes.
> User docker directory instead of Dockerfile for flex

- README.md
- pom.xml
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkMojoTest.java
> Rename project to appengine-maven-plugin

- pom.xml
- src/main/java/com/google/cloud/tools/maven/StageMojo.java
Added more metadata that is required for a release.
Also, added javadoc and artifact signing in a separate 'release' profile.
@patflynn
> Add pom.xml metadata, javadoc, and signing

- pom.xml
> Bump working version to 0.1.1-SNAPSHOT

- .gitignore
- .travis.yml
- appveyor.yml
- src/test/java/com/google/cloud/tools/maven/it/AbstractMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/DeployMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/RunAsyncMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/RunMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/StageMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/StopMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/util/UrlUtils.java
- src/test/java/com/google/cloud/tools/maven/it/verifier/FlexibleVerifier.java
- src/test/java/com/google/cloud/tools/maven/it/verifier/StandardVerifier.java
- src/test/java/com/google/cloud/tools/maven/it/verifier/TailingVerifier.java
* Stream maven output to console for integration tests
* Make Dev App Server tests more robust
> Improve integration tests

- README.md
> Update plugin version and build image in readme

- README.md
@patflynn @loosebazooka @arouzrokh
> mark it as BETA in readme

- pom.xml
- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
- src/main/java/com/google/cloud/tools/maven/StageMojo.java
Fixes #52 
Move up to version 0.1.3-SNAPSHOT of the appengine-plugins-core library
> Fix staging issue for compat Java 8 projects

- appveyor.yml
> Fix for AppVeyor non-interactive Cloud SDK components update

- pom.xml
- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
- src/main/java/com/google/cloud/tools/maven/RunAsyncMojo.java
- src/main/java/com/google/cloud/tools/maven/RunMojo.java
- src/test/java/com/google/cloud/tools/maven/AbstractDevServerTest.java
- src/test/java/com/google/cloud/tools/maven/RunAsyncMojoTest.java
- src/test/java/com/google/cloud/tools/maven/RunMojoTest.java
> Fail early when trying to start dev server with flexible app

- pom.xml
> use 0.1.4 version of appengine-plugins-core

- pom.xml
> Bump the version to 0.1.2-SNAPSHOT following the 0.1.1-beta release

- README.md
> Update README.md with the 0.1.1-beta version

- src/main/java/com/google/cloud/tools/maven/DeployMojo.java
> Fix documentation of deployables parameter

- .travis.yml
- pom.xml
> Update to appengine-plugins-core:0.1.6

- README.md
> Link Readme to public reference docs

- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
Fixes #75.
@lesv Please try with appengine-maven-plugin:0.1.2-SNAPSHOT
@loosebazooka PTAL
> Read maven.compiler.target property to identify Java version

- README.md
- pom.xml
> Bump to version 0.1.3-SNAPSHOT following 0.1.2 release

- README.md
> Update project status in readme

- README.md
- pom.xml
> Bump plugin version to 1.0.0-SNAPSHOT

- pom.xml
> Switch to appengine-plugins-core:0.1.10 release version

- pom.xml
> Update plugin description

- README.md
- pom.xml
minor version change because of new genRepoInfoFile goal.
> Change to version 1.1.0-beta

- src/main/java/com/google/cloud/tools/maven/RunAsyncMojo.java
- src/main/java/com/google/cloud/tools/maven/RunMojo.java
> Fix for old workaround:

- src/test/resources/projects/standard-project/pom.xml
- src/test/resources/projects/standard-project/src/main/webapp/WEB-INF/appengine-web.xml
> Remove application and version from appengine-web.xml test app

- src/main/java/com/google/cloud/tools/maven/DeployMojo.java
- src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java
> Fix "Directories are not supported"

- src/test/java/com/google/cloud/tools/maven/it/StageMojoIntegrationTest.java
The change in #72 was incomplete where it didn't modify the integration test. This fixes it.
> Fix testStageStandard test (module -> service)

- CHANGELOG.md
- README.md
- pom.xml
Updated change log, readme, and current snapshot version.
> Post 1.2.1 release update

- kokoro/release_publish.sh
- kokoro/release_sign.sh
To fit the new build-sign-publish workflow.
> Adds new Kokoro build script for publishing signed artifact to Sonatype.

- kokoro/continuous_mac.sh
> Correctly updates gcloud in continuous_mac.sh

- scripts/prepare_release.sh
> Limits pushing of release tag to not include any other local tags.

- README.md
> 1.3.2 is out

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
> Deprecate cloudSdkPath for cloudSdkHome

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkChecker.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkDownloader.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkOperationsFactory.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkCheckerTest.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkOperationsFactoryTest.java
> Implement cloud sdk checker

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkLoginMojo.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
> Add appengine:cloudSdkLogin goal

- src/main/java/com/google/cloud/tools/maven/CloudSdkLoginMojo.java
> Add cloudSdkLogin help description

- src/main/java/com/google/cloud/tools/maven/AbstractSingleYamlDeployMojo.java
- src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java
- src/main/java/com/google/cloud/tools/maven/StageMojo.java
- src/test/java/com/google/cloud/tools/maven/DeployAllMojoTest.java
> Fix deployAll for flexible projects

- CHANGELOG.md
Meant to add this in the previous commit.
> Add appengineDeployAll to changelog

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/RunAsyncMojo.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/it/RunAsyncMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/RunMojoIntegrationTest.java
> Log devappserver output to file for appengine:start

- src/main/java/com/google/cloud/tools/maven/AbstractDeployMojo.java
- src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java
- src/main/java/com/google/cloud/tools/maven/DeployMojo.java
- src/test/java/com/google/cloud/tools/maven/DeployAllMojoTest.java
- src/test/java/com/google/cloud/tools/maven/it/AbstractMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/it/DeployAllMojoIntegrationTest.java
- src/test/resources/projects/flexible-project/src/main/appengine/app.yaml
> Add integration tests for deployAll, fix deployAll occurring before stage, fix staged yaml directory for standard projects

- src/main/java/com/google/cloud/tools/maven/AbstractDeployMojo.java
- src/main/java/com/google/cloud/tools/maven/DeployAllMojo.java
- src/main/java/com/google/cloud/tools/maven/DeployMojo.java
- src/test/java/com/google/cloud/tools/maven/AbstractDeployMojoTest.java
- src/test/java/com/google/cloud/tools/maven/DeployAllMojoTest.java
- src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java
> Use appengine-web.xml as backup config instead of gcloud global state

- src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java
- src/test/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactoryTest.java
mojo may not be initialized with values if done at mojo
construction time
> Instantiate CloudSdk later

- pom.xml
- src/main/java/com/google/cloud/tools/maven/AbstractDeployMojo.java
- src/main/java/com/google/cloud/tools/maven/AppEngineFlexibleDeployer.java
- src/main/java/com/google/cloud/tools/maven/AppEngineStandardDeployer.java
- src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
- src/main/java/com/google/cloud/tools/maven/ConfigReader.java
- src/main/java/com/google/cloud/tools/maven/RunMojo.java
- src/test/java/com/google/cloud/tools/maven/AppEngineDeployerTest.java
- src/test/java/com/google/cloud/tools/maven/AppEngineFlexibleDeployerTest.java
- src/test/java/com/google/cloud/tools/maven/AppEngineStandardDeployerTest.java
- src/test/java/com/google/cloud/tools/maven/DeployAllMojoTest.java
- src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java
- src/test/java/com/google/cloud/tools/maven/util/SingleYamlFlexibleDeployTestHelper.java
- src/test/java/com/google/cloud/tools/maven/util/SingleYamlStandardDeployTestHelper.java
- project -> projectId
- run now supports projectId
- Update to plugins core 0.6.6
- Fix some deprecated guava Files calls
> project -> projectId, proejctId on run

- src/main/java/com/google/cloud/tools/maven/deploy/AppDeployer.java
- src/test/java/com/google/cloud/tools/maven/deploy/AppDeployerTest.java
> Fix reading version value during deploy

- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkChecker.java
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkDownloader.java
- src/test/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkCheckerTest.java
- src/test/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkDownloaderTest.java
Fixes https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/351
> Only download appengine component if standard-compat

- src/test/java/com/google/cloud/tools/maven/it/AbstractRunMojoIntegrationTest.java
> Increase timeout for server fetch and stop

- pom.xml
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkAppEngineFactory.java
- src/test/java/com/google/cloud/tools/maven/run/RunnerTest.java
> Update to plugins core 0.7.3

- CHANGELOG.md
Oops, should've done this with the release.
> Update CHANGELOG for 2.0.0-rc5

- pom.xml
- also fix scope of maven-verifier dependency to "test"
> Update to plugins core 0.7.4

- kokoro/continuous_mac.sh
internal reference: b/130225695
> Kokoro macos temporary fix - use newer JDK

- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkLoginMojo.java
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployAllMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployCronMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployDispatchMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployDosMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployIndexMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/DeployQueueMojo.java
- src/main/java/com/google/cloud/tools/maven/genrepoinfo/GenRepoInfoFileMojo.java
- src/main/java/com/google/cloud/tools/maven/run/RunAsyncMojo.java
- src/main/java/com/google/cloud/tools/maven/run/RunMojo.java
- src/main/java/com/google/cloud/tools/maven/run/StopMojo.java
- src/main/java/com/google/cloud/tools/maven/stage/StageMojo.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployAllMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployCronMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployDispatchMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployDosMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployIndexMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/DeployQueueMojoTest.java
- src/test/java/com/google/cloud/tools/maven/genrepoinfo/GenRepoInfoFileMojoTest.java
- src/test/java/com/google/cloud/tools/maven/run/RunAsyncMojoTest.java
- src/test/java/com/google/cloud/tools/maven/run/RunMojoTest.java
- src/test/java/com/google/cloud/tools/maven/run/StopMojoTest.java
sorry about the public method, not sure how else to expose this parameter, I guess I could just make the member public?
> Make all goals 'skip' with skip configuration option

- .travis.yml
> Set up OpenJDK 11 build

- src/test/java/com/google/cloud/tools/maven/deploy/DeployerTest.java
- src/test/java/com/google/cloud/tools/maven/it/AbstractRunMojoIntegrationTest.java
- src/test/java/com/google/cloud/tools/maven/run/StopMojoTest.java
> Clean up code

- pom.xml
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkAppEngineFactory.java
- src/main/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkDownloader.java
- src/main/java/com/google/cloud/tools/maven/deploy/AbstractDeployMojo.java
- src/main/java/com/google/cloud/tools/maven/deploy/AppDeployer.java
- src/test/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkAppEngineFactoryTest.java
- src/test/java/com/google/cloud/tools/maven/cloudsdk/CloudSdkDownloaderTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/AbstractDeployMojoTest.java
- src/test/java/com/google/cloud/tools/maven/deploy/AppDeployerTest.java
fixes #374 
```
<configuration>
...
<gcloudMode>beta</gcloudMode>
...
</configuration>
```
> Add gcloudMode config option for beta deploy

- CHANGELOG.md
- pom.xml
This will pull in the Java 17 fix from the last core release.
> Update appengine-plugins-core version

- .github/workflows/prepare-release.yml
To be backed out when actions/checkout#760 is resolved.
> Workaround for permissions to release

- .github/workflows/prepare-release.yml
last try: updating the path to /home/runner/work/app-maven-plugin/app-maven-plugin
> workaround for permission

- pom.xml
To be merged after the release is complete.
> release v2.4.2

- pom.xml
To be merged after the release is complete.
> release v2.4.3

- CHANGELOG.md
- pom.xml
For seamless Java 17 devserver.
> deps: update appengine-plugins-core to 0.9.9

- pom.xml
To be merged after the release is complete.
> release v2.4.4

- CHANGELOG.md
- pom.xml
Releasing v2.5.0. The changelog has been updated accordingly.
> Release v2.5.0
