GoogleCloudPlatform/app-maven-plugin

pom.xml, src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java, src/main/java/com/google/cloud/tools/maven/DeployMojo.java, src/main/java/com/google/cloud/tools/maven/RunAsyncMojo.java, src/main/java/com/google/cloud/tools/maven/RunMojo.java, src/main/java/com/google/cloud/tools/maven/StageMojo.java, src/main/java/com/google/cloud/tools/maven/StopMojo.java
The functionality to wait for an async process to start successfully has been moved to the common tools library. See: https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/pull/67.
Also, changed pom.xml to generated sources jar and to run faster.
=> Use tools lib to handle waiting for dev app server to start

src/main/java/com/google/cloud/tools/maven/CloudSdkMojo.java
In relation to #4.
I'd like to set this now so that we don't forget it before the next release. How about "app-maven-plugin"?
Note: we still need to set ENVIRONMENT_VERSION.
=> Set env var and tag plugin identify for metrics

src/main/java/com/google/cloud/tools/maven/StageMojo.java
This is a sync up with the common tools library change.
@loosebazooka
=> specify appengine config directory rather than app.yaml path

.travis.yml
The default timeout is 10 minutes, but the deployment test can sometimes take longer without producing any output to the console.
@loosebazooka
=> use travis_wait 30 to increase no output timeout to 30 mins

.travis.yml, pom.xml
The Travis deploy test is still unreliable. Removing it until the issue is resolved.
@loosebazooka PTAL
=> Update to Plugins Core 0.1.5-SNAPSHOT and disable Travis remote tests

pom.xml, src/main/java/com/google/cloud/tools/maven/DeployMojo.java
Fixes #71. These two parameters are not longer supported by the Cloud SDK.
@loosebazooka PTAL
=> Removing deploy.dockerBuild and deploy.force parameters

appveyor.yml, pom.xml
Removing installation of Maven in AppVeyor config, since it's now included in the default image.
@loosebazooka PTAL
=> Maven now included in AppVeyor CI

src/test/resources/projects/parent/pom.xml
Integration tests are all failing on my local environment because an ancient version of the maven compiler was being selected by default.
=> Force correct maven-compiler-plugin version on integration tests.

.travis.yml, appveyor.yml, pom.xml, src/main/java/com/google/cloud/tools/maven/AppEngineFactory.java, src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java, src/main/java/com/google/cloud/tools/maven/GenRepoInfoFileMojo.java, src/main/java/com/google/cloud/tools/maven/RunMojo.java, src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java, src/test/java/com/google/cloud/tools/maven/GenRepoInfoFileMojoTest.java, src/test/java/com/google/cloud/tools/maven/it/AbstractMojoIntegrationTest.java, src/test/java/com/google/cloud/tools/maven/it/DeployMojoIntegrationTest.java, src/test/java/com/google/cloud/tools/maven/it/GenRepoInfoFileMojoIntegrationTest.java, src/test/resources/projects/flexible-project/pom.xml
Fixes #100.
This should be ready for early preview. I think I still need to add unit tests here.
For the generation to be done automatically, this has the sad shortcoming that the following needs to be added to the pom.xml of the project using the plugin:
<plugin>
<groupId>com.google.cloud.tools</groupId>
<artifactId>appengine-maven-plugin</artifactId>
<version>1.0.0-SNAPSHOT</version>
>         <executions>
>           <execution>
>             <phase>prepare-package</phase>
>             <goals>
>               <goal>genRepoInfoFile</goal>
>             </goals>
>           </execution>
>         </executions>
</plugin>
=> Adds a genRepoInfoFile goal.

pom.xml, src/main/java/com/google/cloud/tools/maven/DeployMojo.java, src/test/java/com/google/cloud/tools/maven/DeployMojoTest.java
Fixes #131.
This is pending fix in appengine-plugins-core: https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/317
=> Allow app.yaml to be generated by gcloud when deploying

USER_GUIDE.md, pom.xml, src/main/java/com/google/cloud/tools/maven/CloudSdkAppEngineFactory.java, src/main/java/com/google/cloud/tools/maven/RunMojo.java, src/test/java/com/google/cloud/tools/maven/RunMojoTest.java, src/test/java/com/google/cloud/tools/maven/it/RunAsyncMojoIntegrationTest.java, src/test/java/com/google/cloud/tools/maven/it/RunMojoIntegrationTest.java, src/test/resources/projects/standard-project/pom.xml, src/test/resources/projects/standard-project/src/main/java/HelloServlet.java
I don't particularly like how the <environment> parameter is tested in the integration test, but until we add more thorough testing of parameters to integration tests, it'll be OK.
=> update plugins-core to 0.3.2, add <environment> parameter

src/main/java/com/google/cloud/tools/maven/AbstractDeployMojo.java
Reintroduces the parameter (removed in rc2), to provide an effective transition from 1.3.X GA users.
=> Make transition smoother to projectId

kokoro/continuous.bat, kokoro/continuous.sh, kokoro/continuous_mac.sh
Cobertura can't handle Java 8 code, and `./mvnw -U cobertura:cobertura` is failing. Cobertura has been dormant for years regarding Java 8 support and seems almost dead.
=> Remove Cobertura

src/main/java/com/google/cloud/tools/maven/stage/AppYamlStager.java
This allows users to inject arbitrary files into staging using maven `copy-resources` `copy-dependencies` goals
=> do not delete staging directory by default

USER_GUIDE.md
standard -> appengine-web.xml based
flexible -> app.yaml based (now include app.yaml based standard projects)
=> Update docs to reference how projects are handled

README.md, USER_GUIDE.md
You can see the rendered docs on the branch:
* readme: https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/rearrange-docs/README.md
* user_guide: https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/rearrange-docs/USER_GUIDE.md
=> Rearrage docs, add faq for thin jars

pom.xml
Adds extended support for thin jar deployments, automatically copying
jars referenced in Class-Path in the source artifact to the staging
directory.
@ludoch this is all we would need to support this feature in 2.2.0
=> Upgrade plugins-core to 0.8.1

src/main/java/com/google/cloud/tools/maven/run/AbstractRunMojo.java, src/main/java/com/google/cloud/tools/maven/run/Runner.java, src/test/java/com/google/cloud/tools/maven/run/AbstractRunMojoTest.java, src/test/java/com/google/cloud/tools/maven/run/RunnerTest.java
fixes the error message for non appengine-web.xml projects when not specifying a service.
https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/421#issuecomment-642873454
=> Handle empty service config better

CHANGELOG.md, pom.xml
Releasing this plugin to use appengine-plugins-core 0.9.5. Added the changelog.
=> Releasing version 2.4.1

USER_GUIDE.md, pom.xml, src/test/resources/projects/parent/pom.xml, src/test/resources/projects/standard-project/pom.xml
All the plugins are working. I upgraded findbugs to a version somewhat lower than the latest because the latest comes with deeper immutability analysis that's more involved to fix (and not clear it's worth fixing for stable, self-contained code).
The integration test using AppEngine local devserver had to pass the JPMS add-opens parameteres, since devserver does some access modification of JDK classes through reflection. Since JPMS is available only starting at Java 9, I split the sample application appengine plugin into two profiles activated by java versions.
Also, a timezone option needed to be passed to work around an NPE in devserver (it's been fixed in devserver since, but not released yet).
=> Working version with Java 17

README.md, USER_GUIDE.md
The add-opens are now added by appengine-plugins-core.
=> chore: remove workaround for java 17 add-opens

kokoro/continuous.bat
Fixes similar issue as https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/912
=> chore: clean up JAVA_HOME setup

.github/workflows/unit-tests.yaml, CHANGELOG.md, pom.xml
Upgrade appengine-plugins-core to 0.10.0 that supports java21 runtime
=> Upgrade appengine-plugins-core to 0.10.0

kokoro/continuous.sh, kokoro/release_build.sh, pom.xml
- preparing release 2.5.0
- gcloud components upgrade with quiet option
I created this branch based on the existing v2.5.0 tag, so that we can use the updated commit to invoke the release build (without the snapshot version).
=> gcloud components update to use the quiet option

.github/workflows/unit-tests.yaml, pom.xml, spotbugs-exclude.xml
=> chore: set up java 21 in unit tests
